Update CONTRIBUTORS.yaml
elixir-europe/rdmkit pull request #1044
Opened 2022-11-08 14:53 UTC by erlefloch

@langeipk , @sebeier , @proccaserra : I added some minimal information (github handle and orcid id) for your RDMkit contributor profiles, feel free to add more (affiliation and email address for example).

2022-11-09 15:41 UTC, langeipk commented on _data/CONTRIBUTORS.yaml
> +    git: langeipk
email: lange@ipk-gatersleben.e

2022-11-09 15:43 UTC, langeipk commented on _data/CONTRIBUTORS.yaml
> +    orcid: 0000-0002-4316-078X
affiliation: IPK-Gatersleben (ROR: [02skbsp27](https://ror.org/02skbsp27))

2022-11-09 15:45 UTC, langeipk requested changes
You may add my e-mail and affiliation. Because ORCIDS are assigned, I suggest to assign also the particular ROR for the affiliation

2022-11-09 15:49 UTC, bedroesb commented
Currently we only keep track of ROR in the affiliations that in are in the community > Support page

2022-11-09 23:31 UTC, bedroesb commented
@erlefloch do you add this extra info? :)

2022-11-10 08:19 UTC, erlefloch reviewed
@bedroesb  done :)

2022-11-10 08:22 UTC, bedroesb approved these changes

2022-11-10 08:22 UTC, merged