Bioimage update
elixir-europe/rdmkit pull request #1201
Opened 2023-02-14 21:23 UTC by jburel

Adjust page following comment on https://github.com/elixir-europe/rdmkit/issues/1102

2023-02-17 15:11 UTC, bianchini88 requested changes

2023-02-17 15:11 UTC, bianchini88 commented on pages/your_domain/bioimaging_data.md
> + - data acquired in other facility (commissioned work or external guest user) and "transported" by the users to their facility;
It is not immediately clear why the "form" would be different depending on the facility. 
More details should be provided to further enrich this list.

2023-02-17 15:11 UTC, bianchini88 commented on pages/your_domain/bioimaging_data.md
> + - slides scanned for example.
No need to write "for example" within such a list

2023-02-17 15:11 UTC, bianchini88 commented on pages/your_domain/bioimaging_data.md
> +**Open source translators**: Members of the community have developed multi-format translators that can be used to access your data with needing to transform it. You will need to perform this translat
This sentence should be rephrased to make it clearer. E.g. "to access your data with needing to transform it" is not very clear. The word "translator" is used for tools that seem to be "converters".

2023-02-17 15:11 UTC, bianchini88 commented on pages/your_domain/bioimaging_data.md
> +  - [OME-Files](https://www.openmicroscopy.org/ome-files/) - The [Open Microscopy Consortium (OME)](https://www.openmicroscopy.org/) has developed an open format, "OME-TIFF", to which you can convert
"Straightforward", not "straight-forward". Also, what do the authors actually mean by "straightforward" in this case?

2023-02-17 15:11 UTC, bianchini88 commented on pages/your_domain/bioimaging_data.md
> +  - The [bioformats2raw](https://github.com/glencoesoftware/bioformats2raw) and [raw2ometiff](https://github.com/glencoesoftware/raw2ometiff) toolchain provided by [Glencoe Software](https://www.glen
"you might want to give it a try" is possibly too colloquial.

2023-02-17 15:11 UTC, bianchini88 commented on pages/your_domain/bioimaging_data.md
> +  - Which types of access is required for the users e.g. download only, browse search and view data and metadata, API access.
"Which type.... is" or "Which types... are"

2023-02-23 14:52 UTC, bedroesb commented
@bianchini88 I ping you again because you are doing a great job at reviewing, tell me if I should stop doing so ;)

2023-02-23 15:06 UTC, bianchini88 commented
@bedroesb I will review this by the end of the week, possibly tomorrow.
Keep pinging me whenever required.

2023-02-24 09:18 UTC, bianchini88 approved these changes

2023-02-24 09:18 UTC, merged