Update si_resources.md
elixir-europe/rdmkit pull request #1280
Opened 2023-05-25 11:22 UTC by nadja-zlender

2023-05-26 12:57 UTC, Nazeeefa requested changes
Thanks @nadja-zlender can you kindly check if any links are missing e.g. does ARIS have webpage? and if there are links to relevant guidelines/regulations/policies?

2023-05-31 07:23 UTC, nadja-zlender commented
> Thanks @nadja-zlender can you kindly check if any links are missing e.g. does ARIS have webpage? and if there are links to relevant guidelines/regulations/policies?

We still need to check all of it within our group. Can we update the links later?

2023-08-22 13:13 UTC, bedroesb commented on pages/national_resources/si_resources.md
> +coordinators: [Brane Leskošek, Marko Vidak, Nadja Žlender]
I am commenting on the wrong line, but if a few lines down you don't want to specify any specific training from Slovenia, you can delete that specific block.

2023-08-24 11:46 UTC, nadja-zlender commented
> @nadja-zlender any updates? let us know if you need any help :)

I have updated the file.

2023-08-24 12:06 UTC, bedroesb commented
@nadja-zlender Thanks a lot! Polonca Ferk was mentioned as coordinator but not as contributor. You can only be  coordinator if one is also a contributor (it puts the crown on the name). I swapped it for now, but please correct accordingly

2023-08-24 14:25 UTC, bedroesb approved these changes
Looks good on my side!

2023-08-25 08:49 UTC, Nazeeefa requested changes

2023-08-25 08:49 UTC, Nazeeefa commented on pages/national_resources/si_resources.md
> +Some of ELIXIR Slovenia’s activities are funded by the European Union (EU), currently mainly through the ELIXIR-CONVERGE.
The Converge has ended so this sentence can be revised perhaps?

2023-08-29 06:27 UTC, Nazeeefa approved these changes

2023-08-29 06:28 UTC, merged