Update ee_resources.md
elixir-europe/rdmkit pull request #1582
Opened 2024-12-20 13:16 UTC by diana-pilvar

Updated University of Tartu libraries open science page- link was broken

2024-12-29 14:28 UTC, Nazeeefa requested changes

2024-12-29 14:28 UTC, Nazeeefa commented on pages/national_resources/ee_resources.md
> +* [University of Tartu Library](https://utlib.ut.ee/en/content/open-science) open science page. The main focus is on Open Science and Open Access and how to write a Data Management Plan
I'd suggest to hyperlink it as e.g. "[Open Science page by the University of Tartu Library](https://utlib.ut.ee/en/content/open-science)" for all three links

2025-01-02 14:35 UTC, diana-pilvar commented on pages/national_resources/ee_resources.md
>  ### Libraries
done

2025-01-02 14:35 UTC, diana-pilvar commented on pages/national_resources/ee_resources.md
> +* [University of Tartu Library](https://utlib.ut.ee/en/content/open-science) open science page. The main focus is on Open Science and Open Access and how to write a Data Management Plan
done

2025-01-02 14:37 UTC, diana-pilvar commented
@Nazeeefa please check again my new version.

2025-01-02 18:27 UTC, Nazeeefa commented
> @Nazeeefa please check again my new version.

Thanks @diana-pilvar! I checked and had second thoughts to make section look more organised, this way we don't have to have "Other initiatives" section which had only one link. Have a look and let me know what you think!

2025-01-03 07:59 UTC, diana-pilvar commented
@Nazeeefa Yes, this looks better.

2025-01-06 13:49 UTC, Nazeeefa approved these changes

2025-01-06 13:49 UTC, merged